In [112]:
import pandas as pd
import numpy as np
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [113]:
df = pd.read_csv("../01-PRE_PROCESS/social_anxiety_dataset_cleaned.csv")

In [114]:
df.head()

,Age,Gender,Occupation,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Smoking,Family History of Anxiety,Stress Level (1-10),...,Stress Band,Sweating Band,Diet Category,Anxiety Severity,Occupation Sector,Somatic Arousal Score,Recovery Capacity,Stress-Recovery Balance,Sleep-Caffeine Cycle,Inherited Risk Triggered
0,59.0,Other,Teacher,7.0,2.4,40.0,5.0,Yes,No,4,...,Moderate,High,Poor,Minimal,Professional,2,1,Coasting,0,0
1,46.0,Female,Student,5.1,5.4,156.0,11.0,Unknown,No,3,...,Low,High,Poor,Mild,Student,2,1,Coasting,0,0
2,40.0,Other,Lawyer,5.1,1.9,570.0,14.0,Yes,Yes,9,...,Severe,Moderate,Fair,Severe,Professional,2,0,Overloaded,1,1
3,40.0,Male,Nurse,7.6,0.9,129.0,0.0,No,No,9,...,Severe,Low,Poor,Moderate,Healthcare,1,1,Overloaded,0,0
4,26.0,Male,Other,6.7,3.0,64.0,13.0,No,No,10,...,Severe,High,Fair,Mild,Other,2,1,Overloaded,0,0

In [115]:
np.random.seed(42)
n = 300

df_cat = pd.DataFrame({
    "Gender": np.random.choice(
        ["Male", "Female"],
        size=n
    ),

    "City": np.random.choice(
        ["Tehran", "Shiraz", "Tabriz", "Mashhad"],
        size=n
    ),

    "Payment_Type": np.random.choice(
        ["Cash", "Credit", "Debit"],
        size=n
    ),

    "Class": np.random.choice(
        ["A", "B", "C"],
        size=n
    )
})

In [116]:
COLORS = px.colors.qualitative.Safe

ما برای ایجاد قابلیت استفاده ی مجدد کد تمام موارد را به صورت تابعی توسعه می دهیم. همچنین موارد مورد نیاز را با توجه به تعداد متغیر مورد انتظار برای نمایش این توابع را دسته بندی کردیم.

۱. توابع تک متغیره

۲. توابع دو متغیره

۳. توابع سه متغیره

برای هر تابع با توجه به ماهیت تعداد متغیر آن انواع معینی از نمودار تدارک دیدیم.

برای نمایش نمودار تک متغیره کتگوریکال نمودار های میله ای, pie و treemap امکان پذیر و تا حدی منطقی به نظر می رسد.

In [117]:
def categorical_univariate_all_plots(df, column):

    counts = df[column].value_counts().reset_index()

    fig = make_subplots(rows=1, cols=3, subplot_titles=["Bar Chart", "Pie Chart", "Treemap"], specs=[[{"type": "xy"}, {"type": "domain"}, {"type": "domain"}]])

    bar = px.bar(counts, x=column, y="count", color=column, color_discrete_sequence=COLORS, text="count")

    for trace in bar.data:
        fig.add_trace(trace, row=1, col=1)


    pie = px.pie(counts, names=column, values="count", color=column, color_discrete_sequence=COLORS, hole=0.45)

    for trace in pie.data:
        fig.add_trace(trace, row=1, col=2)

    treemap = px.treemap(counts, path=[column], values="count")

    for trace in treemap.data:
        fig.add_trace(trace, row=1, col=3)

    fig.update_layout(
        title_text=f"Univariate Categorical Analysis: {column}",
        height=500
    )

    return fig

In [118]:
def categorical_univariate_plot(df, column, plot_type="bar"):
    counts = df[column].value_counts().reset_index()

    if plot_type == "bar":
        fig = px.bar(counts, x=column, y="count", title=f"Distribution of {column}", labels={"count": "Count"})


    elif plot_type == "pie":
        fig = px.pie(counts, names=column, values="count", title=f"Distribution of {column}")


    elif plot_type == "treemap":
        fig = px.treemap(counts, path=[column], values="count", title=f"Distribution of {column}")

    return fig

تست نمودار های تک متغیره با داده های تولید شده ی رندم:

In [119]:
fig = categorical_univariate_all_plots(df_cat, "Gender")
fig.show()

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

In [120]:
fig = categorical_univariate_all_plots(df_cat, "Gender")
fig.show()

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

In [121]:
fig1 = categorical_univariate_plot(df_cat, "Gender", "bar")
fig1.show()


fig2 = categorical_univariate_plot(df_cat, "City", "pie")
fig2.show()


fig3 = categorical_univariate_plot(df_cat, "Payment_Type", "treemap")
fig3.show()

برای نمایش نمودار دو متغیره کتگوریکال نمودار های میله ای گروهی, stacked bar و heatmap امکان پذیر و تا حدی منطقی به نظر می رسد.

In [122]:
df.columns

Index(['Age', 'Gender', 'Occupation', 'Sleep Hours',
       'Physical Activity (hrs/week)', 'Caffeine Intake (mg/day)',
       'Alcohol Consumption (drinks/week)', 'Smoking',
       'Family History of Anxiety', 'Stress Level (1-10)', 'Heart Rate (bpm)',
       'Breathing Rate (breaths/min)', 'Sweating Level (1-5)', 'Dizziness',
       'Medication', 'Therapy Sessions (per month)', 'Recent Major Life Event',
       'Diet Quality (1-10)', 'Anxiety Level (1-10)', 'Target',
       'Therapy History', 'Sleep Hours Outlier Flag',
       'Physical Activity (hrs/week) Outlier Flag',
       'Caffeine Intake (mg/day) Outlier Flag', 'High Stress Flag',
       'Heart Rate (bpm) Outlier Flag',
       'Therapy Sessions (per month) Outlier Flag', 'Age Group',
       'Sleep Category', 'Activity Level', 'Caffeine Level', 'Drinking Level',
       'Heart Rate Category', 'Breathing Category', 'Therapy Engagement',
       'Stress Band', 'Sweating Band', 'Diet Category', 'Anxiety Severity',
       'Occupation Sector', 'Somatic Arousal Score', 'Recovery Capacity',
       'Stress-Recovery Balance', 'Sleep-Caffeine Cycle',
       'Inherited Risk Triggered'],
      dtype='object')

In [123]:
def categorical_bivariate_all_plots(df, column1, column2, x_order = ["Low", "Medium", "High"]):

    table = pd.crosstab(df[column1], df[column2])

    fig = make_subplots(rows=1, cols=3,subplot_titles=["Grouped Bar", "Stacked Bar", "Heatmap"], specs=[[{"type": "xy"}, {"type": "xy"}, {"type": "heatmap"}]])

    if x_order is None:
        x_order = df[column1].dropna().unique().tolist()
    x_order = [value for value in x_order if value in df[column1].unique()]

    grouped = px.histogram(df, x=column1, color=column2, category_orders={column1: x_order})

    for i, trace in enumerate(grouped.data):
        trace.offsetgroup = f"group_{i}"
        fig.add_trace(trace, row=1, col=1)

    fig.update_xaxes(title_text=column1, categoryorder="array", categoryarray=x_order, row=1, col=1)
    fig.update_yaxes(title_text="Count", row=1, col=1)

    stacked = px.histogram(df, x=column1, color=column2, barmode="stack")

    for trace in stacked.data:
        trace.offsetgroup = "stacked"
        fig.add_trace(trace, row=1, col=2)
    fig.update_xaxes(title_text=column1, row=1, col=2)
    fig.update_yaxes(title_text=column2, row=1, col=2)

    heatmap = px.imshow(table, text_auto=True, color_continuous_scale="Blues", labels={"x": column2, "y": column1, "color": "Count"})

    for trace in heatmap.data:
        fig.add_trace(trace, row=1, col=3)

    fig.update_xaxes(title_text=column2, row=1, col=3)
    fig.update_yaxes(title_text=column1, categoryorder="array", categoryarray=x_order, row=1, col=3)

    fig.update_layout(title_text = f"Bivariate Categorical Analysis: {column1} vs {column2}", height=500)

    return fig

In [124]:
def categorical_bivariate_plot(df, column1, column2, plot_type="grouped_bar"):
    if plot_type == "grouped_bar":
        fig = px.histogram(df, x=column1, color=column2, barmode="group", title=f"{column1} vs {column2}")


    elif plot_type == "stacked_bar":
        fig = px.histogram(df, x=column1, color=column2, barmode="stack", title=f"{column1} vs {column2}")

    elif plot_type == "heatmap":
        table = pd.crosstab(df[column1], df[column2])
        fig = px.imshow(table, text_auto=True, title=f"{column1} vs {column2}")

    return fig

تست نمودار های تک متغیره با داده های تولید شده ی رندم:

In [125]:
df.columns

Index(['Age', 'Gender', 'Occupation', 'Sleep Hours',
       'Physical Activity (hrs/week)', 'Caffeine Intake (mg/day)',
       'Alcohol Consumption (drinks/week)', 'Smoking',
       'Family History of Anxiety', 'Stress Level (1-10)', 'Heart Rate (bpm)',
       'Breathing Rate (breaths/min)', 'Sweating Level (1-5)', 'Dizziness',
       'Medication', 'Therapy Sessions (per month)', 'Recent Major Life Event',
       'Diet Quality (1-10)', 'Anxiety Level (1-10)', 'Target',
       'Therapy History', 'Sleep Hours Outlier Flag',
       'Physical Activity (hrs/week) Outlier Flag',
       'Caffeine Intake (mg/day) Outlier Flag', 'High Stress Flag',
       'Heart Rate (bpm) Outlier Flag',
       'Therapy Sessions (per month) Outlier Flag', 'Age Group',
       'Sleep Category', 'Activity Level', 'Caffeine Level', 'Drinking Level',
       'Heart Rate Category', 'Breathing Category', 'Therapy Engagement',
       'Stress Band', 'Sweating Band', 'Diet Category', 'Anxiety Severity',
       'Occupation Sector', 'Somatic Arousal Score', 'Recovery Capacity',
       'Stress-Recovery Balance', 'Sleep-Caffeine Cycle',
       'Inherited Risk Triggered'],
      dtype='object')

In [126]:
df["Stress Band"].value_counts()

Stress Band
Severe      543
Low         542
Moderate    523
High        422
Name: count, dtype: int64

In [127]:
fig = categorical_bivariate_all_plots(df, "Stress Band", "Target", ["Low", "Moderate", "High", "Severe"])
fig.show()

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

In [128]:
fig2 = categorical_bivariate_all_plots(df, "Family History of Anxiety", "Target")
fig2.show()

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

In [129]:
fig3 = categorical_bivariate_all_plots(df, "Smoking", "Target", ["Unknown", "No", "Yes"])
fig3.show()

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

In [130]:
fig4 = categorical_bivariate_all_plots(df, "Diet Quality (1-10)", "Target")
fig4.show()

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

In [131]:
fig5 = categorical_bivariate_all_plots(df, "Recovery Capacity", "Target")
fig5.show()

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

In [132]:
fig5 = categorical_bivariate_all_plots(df, "Therapy Engagement", "Target")
fig5.show()

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

In [133]:
fig6 = categorical_bivariate_all_plots(df, "Diet Category", "Heart Rate Category", ["Poor","Fair", "Good", "Excellent"])
fig6.show()

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

In [134]:
fig_test = categorical_bivariate_all_plots(df_cat, "Gender", "Payment_Type")
fig_test.show()

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

In [135]:
fig4 = categorical_bivariate_plot(
    df_cat,
    "Gender",
    "Payment_Type",
    "grouped_bar"
)
fig4.show()


fig5 = categorical_bivariate_plot(
    df_cat,
    "Gender",
    "Payment_Type",
    "stacked_bar"
)
fig5.show()


fig6 = categorical_bivariate_plot(
    df_cat,
    "City",
    "Payment_Type",
    "heatmap"
)
fig6.show()

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

/home/mahdiyk2003/miniconda3/envs/quera/lib/python3.11/site-packages/plotly/express/_core.py:1992: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

برای نمایش نمودار دو متغیره کتگوریکال نمودار های facetted_bar و sunburst و treemap و parallel_categories امکان پذیر و تا حدی منطقی به نظر می رسد.

In [136]:
def categorical_trivariate_all_plots(df, column1, column2, column3):

    fig = make_subplots(
        rows=2,
        cols=2,
        subplot_titles=[
            "Faceted Bar",
            "Sunburst",
            "Treemap",
            "Parallel Categories"
        ],
        specs=[
            [{"type": "xy"}, {"type": "domain"}],
            [{"type": "domain"}, {"type": "domain"}]
        ]
    )

    faceted = px.histogram(df, x=column1, color=column2, facet_col=column3, barmode="group")

    for trace in faceted.data:
        fig.add_trace(trace, row=1, col=1)

    sunburst = px.sunburst(df, path=[column1, column2, column3])

    for trace in sunburst.data:
        fig.add_trace(trace, row=1, col=2)

    treemap = px.treemap(df, path=[column1, column2, column3])

    for trace in treemap.data:
        fig.add_trace(trace, row=2, col=1)

    parallel = px.parallel_categories(df, dimensions=[column1, column2, column3])

    for trace in parallel.data:
        fig.add_trace(trace, row=2, col=2)

    fig.update_layout(
        title_text=f"Trivariate Categorical Analysis: {column1}, {column2} and {column3}",
        height=900
    )

    return fig

In [137]:
def categorical_trivariate_plot(df, column1, column2, column3, plot_type="facetted_bar"):
    if plot_type == "facetted_bar":
        fig = px.histogram(df, x=column1, color=column2, facet_col=column3, barmode="group", title=f"{column1}, {column2} and {column3}")

    elif plot_type == "sunburst":
        fig = px.sunburst(df, path=[column1, column2, column3], title=f"{column1} to {column2} to {column3}")

    elif plot_type == "treemap":
        fig = px.treemap(df, path=[column1, column2, column3], title=f"{column1} to {column2} to {column3}")

    elif plot_type == "parallel_categories":

        fig = px.parallel_categories(df, dimensions=[column1, column2, column3], title=f"{column1}, {column2} and {column3}")

    return fig

تست نمودار های سه متغیره با داده های تولید شده ی رندم:

In [138]:
df.columns

Index(['Age', 'Gender', 'Occupation', 'Sleep Hours',
       'Physical Activity (hrs/week)', 'Caffeine Intake (mg/day)',
       'Alcohol Consumption (drinks/week)', 'Smoking',
       'Family History of Anxiety', 'Stress Level (1-10)', 'Heart Rate (bpm)',
       'Breathing Rate (breaths/min)', 'Sweating Level (1-5)', 'Dizziness',
       'Medication', 'Therapy Sessions (per month)', 'Recent Major Life Event',
       'Diet Quality (1-10)', 'Anxiety Level (1-10)', 'Target',
       'Therapy History', 'Sleep Hours Outlier Flag',
       'Physical Activity (hrs/week) Outlier Flag',
       'Caffeine Intake (mg/day) Outlier Flag', 'High Stress Flag',
       'Heart Rate (bpm) Outlier Flag',
       'Therapy Sessions (per month) Outlier Flag', 'Age Group',
       'Sleep Category', 'Activity Level', 'Caffeine Level', 'Drinking Level',
       'Heart Rate Category', 'Breathing Category', 'Therapy Engagement',
       'Stress Band', 'Sweating Band', 'Diet Category', 'Anxiety Severity',
       'Occupation Sector', 'Somatic Arousal Score', 'Recovery Capacity',
       'Stress-Recovery Balance', 'Sleep-Caffeine Cycle',
       'Inherited Risk Triggered'],
      dtype='object')

In [139]:
fig1 = categorical_trivariate_all_plots(df, "Target", "Smoking", "Age Group")
fig1.show()

In [140]:
fig1 = categorical_trivariate_all_plots(df, "Target", "Smoking", "Age Group")
fig1.show()

In [141]:
fig_test = categorical_trivariate_all_plots(df_cat, "Gender", "City", "Payment_Type")
fig_test.show()

In [142]:

fig7 = categorical_trivariate_plot(df_cat, "Gender", "Payment_Type", "Class", "facetted_bar")
fig7.show()


fig8 = categorical_trivariate_plot(df_cat, "City", "Payment_Type", "Class", "sunburst")
fig8.show()


fig9 = categorical_trivariate_plot(df_cat, "City", "Payment_Type", "Class", "treemap")
fig9.show()


fig10 = categorical_trivariate_plot(df_cat, "Gender", "City", "Payment_Type", "parallel_categories")
fig10.show()

In [143]:

np.random.seed(42)

n = 300

df_numeric = pd.DataFrame({
    "Age": np.random.normal(
        loc=30,
        scale=8,
        size=n
    ),

    "Height": np.random.normal(
        loc=175,
        scale=7,
        size=n
    ),

    "Weight": np.random.normal(
        loc=70,
        scale=10,
        size=n
    ),

    "Income": np.random.normal(
        loc=5000,
        scale=1500,
        size=n
    )
})

In [144]:
def numerical_univariate_all_plots(df, column):

    fig = make_subplots(
        rows=1,
        cols=5,
        subplot_titles=["Histogram", "Box Plot", "Violin Plot", "ECDF", "Strip Plot"],
        specs=[[{"type": "xy"}, {"type": "xy"}, {"type": "xy"}, {"type": "xy"}, {"type": "xy"}]]
    )

    histogram = px.histogram(df, x=column)

    for trace in histogram.data:
        fig.add_trace(trace, row=1, col=1)


    box = px.box(df, y=column)

    for trace in box.data:
        fig.add_trace(trace, row=1, col=2)


    violin = px.violin(df, y=column, box=True)

    for trace in violin.data:
        fig.add_trace(trace, row=1, col=3)


    ecdf = px.ecdf(df, x=column)

    for trace in ecdf.data:
        fig.add_trace(trace, row=1, col=4)


    strip = px.strip(df, x=column)

    for trace in strip.data:
        fig.add_trace(trace, row=1, col=5)


    fig.update_layout(
        title_text=f"Numerical Univariate Analysis: {column}",
        height=500,
        showlegend=False
    )

    return fig

In [145]:
def numerical_univariate_plot(df, column, plot_type="histogram"):

    if plot_type == "histogram":

        fig = px.histogram(df, x=column, title=f"Distribution of {column}")

    elif plot_type == "box":

        fig = px.box(df, y=column, title=f"Box Plot of {column}")

    elif plot_type == "violin":

        fig = px.violin(df, y=column, box=True, title=f"Violin Plot of {column}")

    elif plot_type == "ecdf":

        fig = px.ecdf(df, x=column, title=f"ECDF of {column}")

    elif plot_type == "strip":

        fig = px.strip(df, x=column, title=f"Strip Plot of {column}")

    return fig

In [146]:
fig1 = numerical_univariate_all_plots(df_numeric, "Age")
fig1.show()

In [147]:
fig1 = numerical_univariate_plot(df_numeric, "Age", plot_type="histogram")
fig1.show()


fig2 = numerical_univariate_plot(df_numeric, "Age", plot_type="box")
fig2.show()


fig3 = numerical_univariate_plot(df_numeric, "Age", plot_type="violin")
fig3.show()


fig4 = numerical_univariate_plot(df_numeric, "Age", plot_type="ecdf")
fig4.show()


fig5 = numerical_univariate_plot(df_numeric, "Age", plot_type="strip")
fig5.show()

In [148]:
def numerical_bivariate_all_plots(df, column1, column2):

    fig = make_subplots(
        rows=1,
        cols=3,
        subplot_titles=["Scatter Plot", "Density Heatmap", "Density Contour"],
        specs=[[{"type": "xy"}, {"type": "xy"}, {"type": "xy"}]]
    )

    scatter = px.scatter(df, x=column1, y=column2)

    for trace in scatter.data:
        fig.add_trace(trace, row=1, col=1)
    fig.update_xaxes(title_text=column1, row=1, col=1)
    fig.update_yaxes(title_text=column2, row=1, col=1)

    density_heatmap = px.density_heatmap(df, x=column1, y=column2)

    for trace in density_heatmap.data:
        fig.add_trace(trace, row=1, col=2)
    fig.update_xaxes(title_text=column1, row=1, col=2)

    fig.update_yaxes(title_text=column2, row=1, col=2)

    density_contour = px.density_contour(df, x=column1, y=column2)

    for trace in density_contour.data:
        fig.add_trace(trace, row=1, col=3)
    fig.update_xaxes(title_text=column1, row=1, col=3)
    fig.update_yaxes(title_text=column2, row=1, col=3)

    fig.update_layout(
        title_text=f"Numerical Bivariate Analysis: {column1} vs {column2}",
        height=500,
        showlegend=False
    )

    return fig

In [149]:
def numerical_bivariate_plot(df, column1, column2, plot_type="scatter"):

    if plot_type == "scatter":

        fig = px.scatter(df, x=column1, y=column2, title=f"{column1} vs {column2}")

    elif plot_type == "density_heatmap":

        fig = px.density_heatmap(df, x=column1, y=column2, title=f"Density Heatmap: {column1} vs {column2}")

    elif plot_type == "density_contour":

        fig = px.density_contour(df, x=column1, y=column2, title=f"Density Contour: {column1} vs {column2}")

    return fig

In [150]:
df.head()

,Age,Gender,Occupation,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Smoking,Family History of Anxiety,Stress Level (1-10),...,Stress Band,Sweating Band,Diet Category,Anxiety Severity,Occupation Sector,Somatic Arousal Score,Recovery Capacity,Stress-Recovery Balance,Sleep-Caffeine Cycle,Inherited Risk Triggered
0,59.0,Other,Teacher,7.0,2.4,40.0,5.0,Yes,No,4,...,Moderate,High,Poor,Minimal,Professional,2,1,Coasting,0,0
1,46.0,Female,Student,5.1,5.4,156.0,11.0,Unknown,No,3,...,Low,High,Poor,Mild,Student,2,1,Coasting,0,0
2,40.0,Other,Lawyer,5.1,1.9,570.0,14.0,Yes,Yes,9,...,Severe,Moderate,Fair,Severe,Professional,2,0,Overloaded,1,1
3,40.0,Male,Nurse,7.6,0.9,129.0,0.0,No,No,9,...,Severe,Low,Poor,Moderate,Healthcare,1,1,Overloaded,0,0
4,26.0,Male,Other,6.7,3.0,64.0,13.0,No,No,10,...,Severe,High,Fair,Mild,Other,2,1,Overloaded,0,0

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2030 entries, 0 to 2029
Data columns (total 45 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Age                                        2030 non-null   float64
 1   Gender                                     2030 non-null   object
 2   Occupation                                 2030 non-null   object
 3   Sleep Hours                                2030 non-null   float64
 4   Physical Activity (hrs/week)               2030 non-null   float64
 5   Caffeine Intake (mg/day)                   2030 non-null   float64
 6   Alcohol Consumption (drinks/week)          2030 non-null   float64
 7   Smoking                                    2030 non-null   object
 8   Family History of Anxiety                  2030 non-null   object
 9   Stress Level (1-10)                        2030 non-null   int64
 10  Heart Rate (bpm)                           2030 non-null   float64
 11  Breathing Rate (breaths/min)               2030 non-null   int64
 12  Sweating Level (1-5)                       2030 non-null   int64
 13  Dizziness                                  2030 non-null   object
 14  Medication                                 2030 non-null   object
 15  Therapy Sessions (per month)               2030 non-null   int64
 16  Recent Major Life Event                    2030 non-null   object
 17  Diet Quality (1-10)                        2030 non-null   float64
 18  Anxiety Level (1-10)                       2030 non-null   float64
 19  Target                                     2030 non-null   int64
 20  Therapy History                            2030 non-null   object
 21  Sleep Hours Outlier Flag                   2030 non-null   int64
 22  Physical Activity (hrs/week) Outlier Flag  2030 non-null   int64
 23  Caffeine Intake (mg/day) Outlier Flag      2030 non-null   int64
 24  High Stress Flag                           2030 non-null   int64
 25  Heart Rate (bpm) Outlier Flag              2030 non-null   int64
 26  Therapy Sessions (per month) Outlier Flag  2030 non-null   int64
 27  Age Group                                  2030 non-null   object
 28  Sleep Category                             2030 non-null   object
 29  Activity Level                             2030 non-null   object
 30  Caffeine Level                             2030 non-null   object
 31  Drinking Level                             1935 non-null   object
 32  Heart Rate Category                        2030 non-null   object
 33  Breathing Category                         2030 non-null   object
 34  Therapy Engagement                         1613 non-null   object
 35  Stress Band                                2030 non-null   object
 36  Sweating Band                              2030 non-null   object
 37  Diet Category                              2030 non-null   object
 38  Anxiety Severity                           2030 non-null   object
 39  Occupation Sector                          2030 non-null   object
 40  Somatic Arousal Score                      2030 non-null   int64
 41  Recovery Capacity                          2030 non-null   int64
 42  Stress-Recovery Balance                    2030 non-null   object
 43  Sleep-Caffeine Cycle                       2030 non-null   int64
 44  Inherited Risk Triggered                   2030 non-null   int64
dtypes: float64(8), int64(15), object(22)
memory usage: 713.8+ KB

In [152]:
df["Caffeine Intake (mg/day)"].mean()

294.2388806334731

In [153]:
fig2= numerical_bivariate_all_plots(df, "Caffeine Intake (mg/day)", "Anxiety Level (1-10)")
fig2.show()

In [154]:
fig3= numerical_bivariate_all_plots(df, "Caffeine Intake (mg/day)", "Target")
fig3.show()

In [155]:
df["Age"].mean()

39.921747967479675

In [156]:
fig4= numerical_bivariate_all_plots(df, "Age", "Anxiety Level (1-10)")
fig4.show()

In [157]:
fig5= numerical_bivariate_all_plots(df, "Age", "Target")
fig5.show()

In [158]:
df["Physical Activity (hrs/week)"].mean()

2.975165235042206

In [159]:
fig6= numerical_bivariate_all_plots(df, "Physical Activity (hrs/week)", "Anxiety Level (1-10)")
fig6.show()

In [160]:
fig7= numerical_bivariate_all_plots(df, "Physical Activity (hrs/week)", "Target")
fig7.show()

In [161]:
fig6 = numerical_bivariate_plot(df_numeric, "Height", "Weight", plot_type="scatter")
fig6.show()


fig7 = numerical_bivariate_plot(df_numeric, "Height", "Weight", plot_type="density_heatmap")
fig7.show()


fig8 = numerical_bivariate_plot(df_numeric, "Height", "Weight", plot_type="density_contour")
fig8.show()

In [162]:
def numerical_trivariate_all_plots(df, column1, column2, column3):

    fig = make_subplots(rows=1, cols=2, subplot_titles=["3D Scatter Plot", "Scatter Matrix"], specs=[[{"type": "scene"}, {"type": "xy"}]])

    scatter_3d = px.scatter_3d(df, x=column1, y=column2, z=column3,color_continuous_scale="Viridis", opacity=0.75, title=f"3D Scatter: {column1}, {column2}, {column3}")

    scatter_matrix = px.scatter_matrix(df, dimensions=[column1, column2, column3])


    return scatter_3d, scatter_matrix

In [163]:
def numerical_trivariate_plot(df, column1, column2, column3, plot_type="scatter_3d"):

    if plot_type == "scatter_3d":

        fig = px.scatter_3d(df, x=column1, y=column2, z=column3, title=f"{column1}, {column2} and {column3}")

    elif plot_type == "scatter_matrix":

        fig = px.scatter_matrix(df, dimensions=[column1, column2, column3], title=f"Scatter Matrix: {column1}, {column2} and {column3}")

    return fig

In [164]:
df.columns

Index(['Age', 'Gender', 'Occupation', 'Sleep Hours',
       'Physical Activity (hrs/week)', 'Caffeine Intake (mg/day)',
       'Alcohol Consumption (drinks/week)', 'Smoking',
       'Family History of Anxiety', 'Stress Level (1-10)', 'Heart Rate (bpm)',
       'Breathing Rate (breaths/min)', 'Sweating Level (1-5)', 'Dizziness',
       'Medication', 'Therapy Sessions (per month)', 'Recent Major Life Event',
       'Diet Quality (1-10)', 'Anxiety Level (1-10)', 'Target',
       'Therapy History', 'Sleep Hours Outlier Flag',
       'Physical Activity (hrs/week) Outlier Flag',
       'Caffeine Intake (mg/day) Outlier Flag', 'High Stress Flag',
       'Heart Rate (bpm) Outlier Flag',
       'Therapy Sessions (per month) Outlier Flag', 'Age Group',
       'Sleep Category', 'Activity Level', 'Caffeine Level', 'Drinking Level',
       'Heart Rate Category', 'Breathing Category', 'Therapy Engagement',
       'Stress Band', 'Sweating Band', 'Diet Category', 'Anxiety Severity',
       'Occupation Sector', 'Somatic Arousal Score', 'Recovery Capacity',
       'Stress-Recovery Balance', 'Sleep-Caffeine Cycle',
       'Inherited Risk Triggered'],
      dtype='object')

In [165]:
fig3d1, fig_matrix1= numerical_trivariate_all_plots(df, "Caffeine Intake (mg/day)", "Sleep Hours", "Target")

fig3d1.show()
fig_matrix1.show()

In [166]:
fig3d2, fig_matrix2= numerical_trivariate_all_plots(df, "Caffeine Intake (mg/day)", "Sleep Hours", "Anxiety Level (1-10)")

fig3d2.show()
fig_matrix2.show()

In [167]:
fig3d3, fig_matrix3= numerical_trivariate_all_plots(df, "Physical Activity (hrs/week)", "Sleep Hours", "Anxiety Level (1-10)")
fig3d3.show()
fig_matrix3.show()

In [168]:
fig3d4, fig_matrix4= numerical_trivariate_all_plots(df, "Physical Activity (hrs/week)", "Sleep Hours", "Target")
fig3d4.show()
fig_matrix4.show()

In [169]:
fig9 = numerical_trivariate_plot(df_numeric, "Age", "Height", "Weight", plot_type="scatter_3d")
fig9.show()


fig10 = numerical_trivariate_plot(df_numeric, "Age", "Height", "Weight",plot_type="scatter_matrix")

fig10.show()

باید ابتدا ستون های عددی را جدا کنیم.

این تابع با متد Pearson بین ستون های عددی correlation را محاسبه می کند.

In [170]:
def numerical_correlation_heatmap(df):
    
    corr = df.corr()

    fig = px.imshow(corr, text_auto=".2f", color_continuous_scale="RdBu_r", zmin=-1, zmax=1, title="Correlation Heatmap")

    return fig

In [171]:
fig = numerical_correlation_heatmap(df)
fig.show()

ValueError: could not convert string to float: 'Other'